### ISSUE TITLE
Unable to create new branch

### ISSUE THREAD

**Issue by colinlowenberg** [memser-spaceport/labweek24-events#44]
I get a 403 error when trying to create a new branch via push commandline.  Attaching my event JSON here.
[happy_halving_day.json](https://github.com/memser-spaceport/labweek24-events/files/14972026/happy_halving_day.json)

**Comment by pandeyanujk** [comment]
Thanka for the info @colinlowenberg. We will take a look at the json and get back. We haven't run into this issue so would be great to get more details around how you got the 403 error. 

@laeccles can you review the event json & let us know if this is good to go. @WinsCodes once you hear from her can you create a PR for this and tag Colin and I on it?

**Comment by pandeyanujk** [comment]
Hey @colinlowenberg I looked [into this](https://lu.ma/hadronfc-dabl-sf-demo-apr19) a bit. Since the event is not affiliated with Funding the Commons & doesn't fall into the category of public goods we won't be able to put it up on the schedule. 

More than happy to add it to the LabWeek24 Public Goods Telegram Channel though so all the attendees can be aware of this event. Let me know.
